export default {
  login: 'abdrr97',
  id: 42917967,
  node_id: 'MDQ6VXNlcjQyOTE3OTY3',
  avatar_url: 'https://avatars.githubusercontent.com/u/42917967?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/abdrr97',
  html_url: 'https://github.com/abdrr97',
  followers_url: 'https://api.github.com/users/abdrr97/followers',
  following_url: 'https://api.github.com/users/abdrr97/following{/other_user}',
  gists_url: 'https://api.github.com/users/abdrr97/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/abdrr97/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/abdrr97/subscriptions',
  organizations_url: 'https://api.github.com/users/abdrr97/orgs',
  repos_url: 'https://api.github.com/users/abdrr97/repos',
  events_url: 'https://api.github.com/users/abdrr97/events{/privacy}',
  received_events_url: 'https://api.github.com/users/abdrr97/received_events',
  type: 'User',
  site_admin: false,
  name: 'Abdrr97',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: true,
  bio:
    'I m a full stack web developer using latest technologies in the market right now frameworks as Angular 8 and Vue Js , Asp.net Core 2.3 and Laravel 5.7 ',
  twitter_username: null,
  public_repos: 17,
  public_gists: 0,
  followers: 1,
  following: 3,
  created_at: '2018-09-02T20:44:09Z',
  updated_at: '2021-02-22T21:22:23Z',
}
